---
- name: Setup database user
  delegate_to: "{{ stocks_postgresql_ansible_host }}"
  become: True
  become_user: "{{ stocks_postgresql_admin_user }}"
  postgresql_user:
    name: "{{ stocks_postgresql_options.user }}"
    password: "{{ stocks_postgresql_options.password }}"
  register: user_presence

- name: Setup database
  delegate_to: "{{ stocks_postgresql_ansible_host }}"
  become: True
  become_user: "{{ stocks_postgresql_admin_user }}"
  postgresql_db:
    name: "{{ stocks_postgresql_database }}"
    owner: "{{ stocks_postgresql_options.user }}"
  register: db_presence

- name: Copy SQL for first stocks user
  template:
    src: initial_user.sql.j2
    dest: "{{ stocks_remote_pkg_dir }}/initial_user.sql"
  when: db_presence.changed

- name: Fill database
  delegate_to: "{{ stocks_postgresql_ansible_host }}"
  become: True
  become_user: "{{ stocks_postgresql_admin_user }}"
  postgresql_db:
    name: "{{ stocks_postgresql_database }}"
    state: restore
    target: "{{ item }}"
  when: db_presence.changed
  with_items:
    - "{{ stocks_base }}/schema.sql"
    - "{{ stocks_remote_pkg_dir }}/initial_user.sql"

