---
- name: Install from file
  include_tasks: package_installation.yml
  when: not stocks_assume_repo_installed

- name: Install from repository
  include_tasks: repo_installation.yml
  when: stocks_assume_repo_installed

- name: Configure stocks
  become: True
  template:
    src: stocks.properties.j2
    dest: "{{ stocks_etc }}/stocks.properties"
    owner: "{{ stocks_tomcat_user }}"
    group: "{{ stocks_tomcat_user }}"
    mode: 0644

- name: Link server.war
  become: True
  file:
    src: "{{ stocks_lib }}/server.war"
    dest: "{{ stocks_tomcat_root }}/webapps/server.war"
    owner: "{{ stocks_tomcat_user }}"
    group: "{{ stocks_tomcat_user }}"
    state: link

- name: Install tomcat config
  become: True
  copy:
    src: "{{ stocks_base }}/server.xml"
    dest: "{{ stocks_tomcat_root }}/conf/server.xml"
    remote_src: True
    owner: "{{ stocks_tomcat_user }}"
    group: "{{ stocks_tomcat_user }}"
    backup: True

- name: Start tomcat
  become: True
  service:
    name: "{{ stocks_tomcat_service }}"
    state: started
    enabled: True

- name: Setup database
  include_tasks: db_setup.yml

- name: Create CA
  become: True
  become_user: "{{ stocks_tomcat_user }}"
  command: "{{ stocks_lib }}/setup-ca {{ stocks_base }}/root/CA {{ stocks_base }}"
  args:
    creates: "{{ stocks_base }}/root/CA"

- name: Create download points
  become: True
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: True
    owner: "{{ stocks_tomcat_user }}"
    group: "{{ stocks_tomcat_user }}"
  with_items:
    - src: "{{ stocks_base }}/root/CA/certs/ca.cert.pem"
      dest: "{{ stocks_base }}/root/nginx/ca"
    - src: "{{ stocks_base }}/root/CA/intermediate/certs/ca-chain.cert.pem"
      dest: "{{ stocks_base }}/root/nginx/chain"

- name: Create nginx SSL
  become: True
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: "{{ stocks_tomcat_user }}"
    group: "{{ stocks_tomcat_user }}"
    mode: 0700

- name: Copy key material
  become: True
  copy:
    src: "{{ item.src }}"
    dest: "/etc/nginx/ssl/{{ item.dest }}"
    remote_src: True
    owner: "{{ stocks_tomcat_user }}"
    group: "{{ stocks_tomcat_user }}"
    mode: 0400
  with_items:
    - src: "{{ stocks_base }}/root/CA/certs/ca.cert.pem"
      dest: ca.cert.pem
    - src: "{{ stocks_base }}/root/CA/intermediate/certs/ca-chain.cert.pem"
      dest: ca-chain.cert.pem
    - src: "{{ stocks_base }}/root/CA/intermediate/certs/server.cert.pem"
      dest: server.cert.pem
    - src: "{{ stocks_base }}/root/CA/intermediate/private/server.key.pem"
      dest: server.key.pem

- name: Generate dhparams
  become: True
  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096
  args:
    creates: /etc/nginx/ssl/dhparam.pem

- name: Add nginx reload to sudoers
  become: True
  copy:
    content: "{{ stocks_sudoers_line }}"
    dest: "/etc/sudoers.d/stocks"
    owner: root
    group: root
    mode: 0400
    validate: /usr/bin/visudo -cf %s

- name: Install nginx config conservatively
  become: True
  copy:
    src: "{{ stocks_base }}/nginx.example.conf"
    dest: /etc/nginx/nginx.conf
    remote_src: True
    owner: root
    group: root
    mode: 0644
    backup: True

- name: Reload nginx
  become: True
  service:
    name: nginx
    state: reloaded

- name: Start nginx server
  become: True
  service:
    name: nginx
    state: started
    enabled: True

- name: Wait for Tomcat startup
  wait_for:
    host: 127.0.0.1
    port: 10915
    state: started
